Name = Arav Mahind

Branch-Div = CMPN-A

Roll = 24102A2008

Subject = R Programming

Assignment = Week 05

In [ ]:
X <- NA

In [ ]:
is.na(X)

[1] TRUE

In [ ]:
x = c(11, NA, 13, NA)

In [ ]:
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [ ]:
mean(x)

[1] NA

In [ ]:
mean(x, na.rm = TRUE)

[1] 12

Missing data: Location of missing values

In [ ]:
which(is.na(x))

[1] 2 4

Missing data

In [ ]:
sum(is.na(x))

[1] 2

Missing data: Finding complete cases

In [ ]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

Missing data: Finding complete data set

In [ ]:
y = na.omit(x)

In [ ]:
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

Missing data: Handling values

In [ ]:
mean(x)

[1] NA

In [ ]:
mean(y)

[1] 12

Conditional Executions – If and If‐Else

1. Conditional execution: if()

In [ ]:
x = 5

In [ ]:
if(x>4) x*3

[1] 15

In [ ]:
if(x>4) {
  x*3
}

[1] 15

In [ ]:
if(x>7) x*3

In [ ]:
if(x>3) {
  print("Value is greater than 3")
}

[1] "Value is greater than 3"

2. Conditional execution: if else()

In [ ]:
x = 5

In [ ]:
if(x>7) {
  x = x-1
} else {
  x = x+1
}

In [ ]:
x

[1] 6

In [ ]:
if(x>3) {
  print("Value is greater than 3")
} else {
  print("Value is less than 3")
}

[1] "Value is greater than 3"

Conditional Executions – Nested if else if and
ifelse

3. Conditional execution: Nested if else if()

In [ ]:
x = 5

In [ ]:
if(x == 3) {
  print("x is 3")
} else if(x == 5) {
  print("x is 5")
} else {
  print("x is neither 3 nor 5")
}

[1] "x is 5"

In [ ]:
x = 1:10

4. Conditional execution: ifelse()

In [ ]:
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
ifelse(x<6, x^2, x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [ ]:
ifelse(x %% 2, "even number", "odd number")

 [1] "even number" "odd number"  "even number" "odd number"  "even number"
 [6] "odd number"  "even number" "odd number"  "even number" "odd number"

Functions for Conditional Executions – switch   
and which commands

In [ ]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [ ]:
switch("colour", "colour" = "blue", "gender" = "male")

[1] "blue"

In [ ]:
x = c(10, 15, 8, 14, 6, 12)

In [ ]:
x

[1] 10 15  8 14  6 12

In [ ]:
which(x == 14)

[1] 4

In [ ]:
which(x != 12)

[1] 1 2 3 4 5

In [ ]:
which(x > 10)

[1] 2 4 6

In [ ]:
x = matrix(nrow=3, ncol=3, data=1:9)

In [ ]:
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [ ]:
which.min(x)

[1] 1

In [ ]:
which.max(x)

[1] 9

In [ ]:
which(x %% 2 == 1)

[1] 1 3 5 7 9

In [ ]:
which(x %% 2 == 1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3